### PR TITLE
Samuelstjean piesno fix

### PR DESCRIPTION
**Pull request by arokem**
You can get that fix into your branch by merging this pull request, but note: before doing that, you will need to rebase your branch on current master to get bago's CSD-related commits out of here.

### CODE REVIEW

**Comment by samuelstjean** [comment]
ok, this so does not work, I'll just rewrite everything.

**Comment by arokem** [comment]
Why are you saying this is not working? The Travis build hasn't even
started running yet.

**Comment by samuelstjean** [comment]
Well, for some reason there is two _piesno_3D functions in the code after the rebase, which is of course incorrect.

**Comment by samuelstjean** [comment]
https://github.com/arokem/dipy/blob/d18b32329566e2cd5a9b59d4cebd52e25d95bff4/dipy/denoise/noise_estimate.py

This version has the two same function definition, one is the old and the other the new one, could that be causing the problem?

**Comment by arokem** [comment]
Well, one's `_piesno_3D` and the other is `piesno_3D` (sans initial
underscore). That's not good, I gather?

**Comment by arokem** [comment]
They seem to be very different in terms of what they actually do

**Comment by samuelstjean** [comment]
The first piesno_3D is not supposed to be there, it's the same as the piesno function, which is a wrapper calling the _piesno_3D function in a loop.

**Comment by arokem** [comment]
Gotcha. Well - you can add commits to your PR, or make a new one. Whichever
works for you.

**Pull request merged**
